### ISSUE TITLE
Roofs tiles do not take on ambient lighting

### ISSUE THREAD

**Issue by baileywick** [League-of-Foundry-Developers/roofs#1]
When the ambient light is lowered in a scene, Roofs tiles still look like they are in bright daylight.

**Comment by Moerill** [comment]
With the current way foundry is doing lighting, this would also mean that roofs would get illuminated by light sources below them. 

is this smth wanted?

If not.. should it stay the current way?

Or what would the ideal case be exactly?

**Comment by baileywick** [comment]
If that's the trade-off, then it's better to hide the lighting below them.

MLT has a function to add an optional hue to a token that's in a
"projected" MLT region. I wonder if you could use something similar to set
a default "darkness" hue that engages at a certain ambient light level?

**Comment by Moerill** [comment]
https://user-images.githubusercontent.com/26152015/104463421-0e74b000-55b2-11eb-8973-9632a113e73f.mp4



one alternative i found, after some quick testing and searchign, is hiding the light while the roof is visible, else showing it... doing the walls right could be the tricky part then though (i gotta admit my mapmaking skills in foundry are very low :sweat_smile: )

EDIT: replaced video by a less extreme and eye hurting example...

**Comment by baileywick** [comment]
Generally, you want to see the whole roof from the outside. I have to do
wall gymnastics to make that effect work. All invisible walls and one-way
walls.

But of you're suggesting to shroud the whole roof in darkness at all times,
even in bright daylight, then I think most wouldn't be happy with it.

Would you like me to send a quick gif on how Grand implemented the hue
change? You would have to be able to detect the ambient lighting level for
this route to be useful. Not sure if that's available to you.

**Comment by Moerill** [comment]
https://user-images.githubusercontent.com/26152015/104475217-1e46c100-55bf-11eb-8dc4-f1fa5debd4cb.mp4

So.. how about like this?

**Comment by Moerill** [comment]
Its trying to immitate the darknesstint. Its probably not perfect for all cases, but pretty close i think.

And its over the lighting layer, so not affected by any lights.
