### ISSUE TITLE
Feature Request: Toggle for outdoor treetop scene

### ISSUE THREAD

**Issue by BigTug** [League-of-Foundry-Developers/roofs#10]
Request for a additional toggle for outdoor treetop tile scene. When treetop tile is set to "Send to Roof " and toggle selected then when an actor token goes under the treetop tile the treetop tile would go opaque and all other actors could see his/her tokens position.  
Currently only the owner can see his/her actor token position, this is good if you are inside a structure with walls and roof. If it is an outdoors scene and another actor token is under a nearby treetop tile they cannot see each others token even if their vision radius would allow them too.
Thank you for the great module and I hope we can see this function or a better solution added to a future release.

**Comment by anthonyronda** [comment]
@BigTug we're considering archiving this repo, but if you have any final thoughts on any of the open issues, get them in soon! I don't think the current 0.8.6 core overhead tiles covers this feature request, but theripper93 is giving a lot of attention to [Better Roofs](https://github.com/theripper93/Better-Roofs/) and related modules so it's a good bet to chat about more ideas over there or on the League Discord
