### ISSUE TITLE
Sending a tile to the roof makes it invisible

### ISSUE THREAD

**Issue by zacdemon** [League-of-Foundry-Developers/roofs#11]
As title. When I send a tile to the roof it becomes completely invisible instead of being transparent when hovered. Tested on fresh world with no other modules using both the DnD 5e and PF2E systems. 

Not sure if I'm doing something wrong.

![image](https://user-images.githubusercontent.com/22028379/112671721-e965ae80-8e38-11eb-918e-b82a6dcb677c.png)

![image](https://user-images.githubusercontent.com/22028379/112671661-d94dcf00-8e38-11eb-8068-54619303c582.png)

**Comment by anthonyronda** [comment]
@zacdemon we're considering archiving this repo. Sorry we couldn't resolve this for you, but if you have any final thoughts on any of the open issues, get them in soon! I hope you're able to update the core Foundry software for a Foundry-native solution that has less bugs 😄

You may or may not be aware but theripper93 is giving a lot of attention to [Better Roofs](https://github.com/theripper93/Better-Roofs/) and related modules so it's a good bet to chat about extensions to 0.8.x overhead tiles over there or on the League Discord

**Comment by zacdemon** [comment]
@anthonyronda You can mark this as resolved. I think the issue was fixed with an update the module received before the release of 0.8.x.
