### ISSUE TITLE
Feature Request: Height-Triggered Roof, simplest case

### ISSUE THREAD

**Issue by pesky-wobbit** [League-of-Foundry-Developers/roofs#14]
I'm using this module with the Wall Height module to allow players to enter 1 story buildings OR run along the rooftops. To handle the rooftops, I currently have to set the token height and then change the roof tile from a roof to a floor. Would it be difficult to automate the second step - in other words, to auto-toggle a roof to a floor when all tokens in the area are at 10+ feet - and then back again when there's at least one down below? 

(To keep it simple and avoid confusion, I think that if If at least one token is down below, the roof remains hidden as normal. We can still identify the rooftop token based on its displayed height.)

**Comment by anthonyronda** [comment]
we're considering archiving this repo, but if you have any final thoughts on any of the open issues, get them in soon! I know the current 0.8.6 core overhead tiles *doesn't* cover this feature request, but theripper93 is giving a lot of attention to [Better Roofs](https://github.com/theripper93/Better-Roofs/) and related modules so it's a good bet to chat about more ideas over there or on the League Discord
