### ISSUE TITLE
REQUEST: Add option for roofs to not be above the Lights layer

### ISSUE THREAD

**Issue by GambetTV** [League-of-Foundry-Developers/roofs#15]
Right now, I'm having an issue where if I want to put a local light source (such as a torch) above a rooftop, I can't use your module, because switching a tile to Roof mode puts it above the light level, making it unaffected by anything other than the map's Darkness Level. This can make rooftops look very out of place when using lots of ambient light sources! So a toggle to swap it to another layer could be cool!

**Comment by anthonyronda** [comment]
@GambetTV we're considering archiving this repo, but if you have any final thoughts on any of the open issues, get them in soon! I don't know if the current 0.8.6 core overhead tiles covers this feature request, but theripper93 is giving a lot of attention to [Better Roofs](https://github.com/theripper93/Better-Roofs/) and related modules so it's a good bet to chat about more ideas over there or on the League Discord
