### ISSUE TITLE
Visual Change on Tool Bar and Drag & Drop Token Blocked in FVTT 0.8.6

### ISSUE THREAD

**Issue by Harshmage** [League-of-Foundry-Developers/roofs#19]
Just upgraded my FVTT to the latest 0.8.6 Stable release, and Roofs is causing a bit of an issue.  Disabling it restores the functionality.

The tool bar on the left side will change the function to the major category you choose, but will not update graphically.  So I can click on the Measurement controls, but it will not highlight in orange, and the submenu controls do not change.  I can lay down a circular measurement (the first, default selection), so the actual function is there.

Also, adding a new token to the map does not work.  Drag and drop all day long, the token will not appear.  Existing tokens can be selected and moved about, even deleted.

**Comment by anthonyronda** [comment]
@Harshmage sorry, with the addition of the overhead tiles feature in 0.8.x core Foundry, roofs is officially deprecated. This makes roofs 0.7.x-only

we're considering archiving this repo, but if you have any final thoughts on any of the open issues, get them in soon! You may or may not be aware, but theripper93 is giving a lot of attention to [Better Roofs](https://github.com/theripper93/Better-Roofs/) and related modules so it's a good bet to chat about more ideas for how to extend core overhead tiles over there, or on the League Discord
