### ISSUE TITLE
Feature Request: hide walls when Roof is visible.

### ISSUE THREAD

**Issue by baileywick** [League-of-Foundry-Developers/roofs#5]
Wondering if it's possible to hide walls under the roof when it's visible. This seems may be technically possible since the Wall Height module can remove line-of-site obstruction of walls. 

The challenge would be how to maintain the entire building still blocking line of sight when standing outside of it. Possible solution: ignore Terrain walls, then surround the entire building in Terrain walls.

**Comment by r2roberts** [comment]
Yes, please.

Though this can get very complicated quickly. Do you want to be able to see things inside the building from standing at an outside window? I think that this will have to become a core capability in a very distant future version of fvtt.

Just hiding the walls under the roof would be a big plus for me.
