### ISSUE TITLE
Issues when an NPC is in a building

### ISSUE THREAD

**Issue by FatBiscuit** [League-of-Foundry-Developers/roofs#8]
When I have an NPC actor in a building, the roof is set to open, allowing all my PCs to see under the roof even if they're outside of the building.  Is this a bug or is there a setting someone to only trigger the under-the-roof reveal for PC's?

**Comment by rice4meplz** [comment]
@FatBiscuit If the players have either Owner or Observer permission on the token, the module will have it render roofs transparent when that token is inside the bounds of the roof.  You can change this in line 205 of RoofsLayer.js
.filter((token)` => token.observer)
replace with
.filter((token) => token.owner)
This will have it set so only OWNERS of the token inside the boundary will render roofs transparent

**Comment by FatBiscuit** [comment]
Actually, the issue was my own stupidity.  I could see inside the buildings while an NPC was present, but my players could only see inside when THEY THEMSELVES were inside.  In other words, there was never actually an issue.  Thanks!

**Comment by anthonyronda** [comment]
Thanks for the followup @FatBiscuit! I'll close this now

As an aside, with the release of 0.8.6 we're considering archiving this repo. If you have any final thoughts on any of the open issues, get them in soon! theripper93 is giving a lot of attention to [Better Roofs](https://github.com/theripper93/Better-Roofs/) and related modules so it's a good bet to chat about more ideas over there or on the League Discord
